/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2020-12-01 08:32:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Rian_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Rian company</title>\r\n");
      out.write("    \r\n");
      out.write("    <!--스타일시트 등록-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!--제이쿼리 등록-->\r\n");
      out.write("    <script src=\"./js/jquery-2.1.3.min.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"./js/jquery.vide.min.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"./js/jquery.scrollTo.min.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <!--제이쿼리 작성-->\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $('nav a').click(function(e){\r\n");
      out.write("            $.scrollTo(this.hash||0, 280);\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("        });\r\n");
      out.write("        $('#btn_gotop').click(function(e){\r\n");
      out.write("            $.scrollTo(this.hash||0, 280);\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(function () {\r\n");
      out.write("            var trigger = $('#trigger');\r\n");
      out.write("            var menu = $('nav ul');\r\n");
      out.write("            $(trigger).on('click', function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                menu.slideToggle();\r\n");
      out.write("            });\r\n");
      out.write("            $(window).resize(function () {\r\n");
      out.write("                var w = $(window).width();\r\n");
      out.write("                if(w>320 && menu.is(':hidden')) {\r\n");
      out.write("                    menu.removeAttr('style');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!--제이쿼리 작성 끝-->\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <nav class=\"clearfix\">\r\n");
      out.write("\t        <ul class=\"clearfix\">\r\n");
      out.write("\t            <li><a href=\"#1\">Overview</a></li>\r\n");
      out.write("\t            <li><a href=\"#2\">Tech</a></li>\r\n");
      out.write("\t            <li><a href=\"#3\">BADARO</a></li>\r\n");
      out.write("\t            <li><a href=\"#4\">Main Tech</a></li>\r\n");
      out.write("\t            <li><a href=\"#11\">Certification</a></li>\r\n");
      out.write("\t            <li><a href=\"#12\">B & P</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t        <a href=\"\" id=\"trigger\"></a>\r\n");
      out.write("\t    </nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--본문-->\r\n");
      out.write("\t    ");
for(int i=1; i<14; i++) { 
      out.write("\r\n");
      out.write("\t    <div id=\"container\" class=\"page");
      out.print(i);
      out.write("\">\r\n");
      out.write("\t    \t<section id=\"");
      out.print(i);
      out.write("\" style=\"width: 0.1px; height: 0.1px;\"></section>\r\n");
      out.write("\t    \t\t<img src=\"./images/");
      out.print(i);
      out.write(".png\" style=\"width: 100%;\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    ");
 } 
      out.write("\r\n");
      out.write("\t    <!--본문 끝-->\r\n");
      out.write("    \r\n");
      out.write("    \t<!--최상단 이동-->\r\n");
      out.write("\t    <a href=\"#1\" id=\"btn_gotop\" class=\"btn_gotop\">\r\n");
      out.write("\t    \t<img src=\"../images/topbutton.png\" style=\"width:80px; display: block; margin: 240px; \"> \r\n");
      out.write("\t\t  \t<span class=\"glyphicon glyphicon-chevron-up\">\r\n");
      out.write("\t\t  \t</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<!--이동 끝-->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
